steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tareas-back:latest'
      - '.'
    id: 'build'
    
  # Push image with commit SHA
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
    id: 'push-sha'
    waitFor: ['build']
  
  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/tareas-back:latest'
    id: 'push-latest'
    waitFor: ['build']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tareas-back'
      - '--image=gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
      - '--region=us-west1'
      - '--platform=managed'
      - '--port=5000'
      - '--cpu=2'
      - '--memory=1Gi'
      - '--timeout=300'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--allow-unauthenticated'
      # Performance optimizations
      - '--no-cpu-throttling'
      - '--cpu-boost'
      # Environment variables
      # IMPORTANT: Configure these properly before deploying!
      # Option 1: Set inline (NOT recommended for production)
      - '--set-env-vars=ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173'
      - '--set-env-vars=LOG_LEVEL=INFO'
      - '--set-env-vars=RUN_DB_SETUP=0'
      - '--set-env-vars=RUN_DB_CREATION=0'
      - '--set-env-vars=cache_enabled=False'
      # Option 2: Use placeholders - configure after deployment
      # Run: gcloud run services update tareas-back --region=us-west1 --set-env-vars=...
      # Required variables that MUST be set:
      # - postgres_user
      # - postgres_password  
      # - postgres_base
      # - AUTH_URL
      # - REALM
      # - AUDIENCE
    id: 'deploy'
    waitFor: ['push-sha', 'push-latest']
    # Option 3: Use Secret Manager (recommended for production)
    # Uncomment secretEnv below and availableSecrets section at the bottom
    # secretEnv: ['POSTGRES_USER', 'POSTGRES_PASSWORD', 'POSTGRES_BASE', 'AUTH_URL', 'REALM', 'AUDIENCE']

images:
  - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/tareas-back:latest'

# Build configuration
timeout: '1800s'  # 30 minutes

options:
  machineType: 'E2_HIGHCPU_8'  # Use more powerful machine for faster builds
  logging: CLOUD_LOGGING_ONLY

# Secrets from Secret Manager (opcional - descomenta si usas Secret Manager)
# availableSecrets:
#   secretManager:
#   - versionName: projects/$PROJECT_ID/secrets/postgres-user/versions/latest
#     env: 'POSTGRES_USER'
#   - versionName: projects/$PROJECT_ID/secrets/postgres-password/versions/latest
#     env: 'POSTGRES_PASSWORD'
#   - versionName: projects/$PROJECT_ID/secrets/postgres-base/versions/latest
#     env: 'POSTGRES_BASE'
