steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tareas-back:latest'
      - '.'
    id: 'build'
    
  # Push image with commit SHA
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
    id: 'push-sha'
    waitFor: ['build']
  
  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/tareas-back:latest'
    id: 'push-latest'
    waitFor: ['build']
  
  # Deploy to Cloud Run - MINIMAL (no env vars)
  # Configure env vars separately with: ./configure-env.sh
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tareas-back'
      - '--image=gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
      - '--region=us-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
    id: 'deploy'
    waitFor: ['push-sha', 'push-latest']

images:
  - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/tareas-back:latest'

timeout: '1800s'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
