steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tareas-back:latest'
      - '.'
    id: 'build'
    
  # Push image with commit SHA
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
    id: 'push-sha'
    waitFor: ['build']
  
  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/tareas-back:latest'
    id: 'push-latest'
    waitFor: ['build']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tareas-back'
      - '--image=gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
      - '--region=us-west1'
      - '--platform=managed'
      - '--port=5000'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--timeout=300'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--allow-unauthenticated'
      # ⚠️ REQUIRED: Configure these environment variables
      # Either here or separately with: gcloud run services update
      # Uncomment and set values:
      # - '--set-env-vars=postgres_user=YOUR_USER'
      # - '--set-env-vars=postgres_password=YOUR_PASSWORD'
      # - '--set-env-vars=postgres_base=YOUR_HOST:5432/YOUR_DB'
      # - '--set-env-vars=AUTH_URL=YOUR_KEYCLOAK_URL'
      # - '--set-env-vars=REALM=YOUR_REALM'
      # - '--set-env-vars=AUDIENCE=YOUR_AUDIENCE'
      - '--set-env-vars=CORS_ORIGINS=https://your-frontend.com,http://localhost:5173'
      - '--set-env-vars=CORS_ALLOW_CREDENTIALS=true'
      - '--set-env-vars=LOG_LEVEL=INFO'
      - '--set-env-vars=RUN_DB_SETUP=0'
      - '--set-env-vars=RUN_DB_CREATION=0'
    id: 'deploy'
    waitFor: ['push-sha', 'push-latest']

images:
  - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/tareas-back:latest'

# Build configuration
timeout: '1800s'  # 30 minutes

options:
  machineType: 'E2_HIGHCPU_8'  # Use more powerful machine for faster builds
  logging: CLOUD_LOGGING_ONLY
