steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tareas-back:latest'
      - '.'
    id: 'build'
    
  # Push image with commit SHA
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
    id: 'push-sha'
    waitFor: ['build']
  
  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/tareas-back:latest'
    id: 'push-latest'
    waitFor: ['build']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tareas-back'
      - '--image=gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
      - '--region=us-west1'
      - '--platform=managed'
      - '--port=5000'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--timeout=300'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--allow-unauthenticated'
      # Add your environment variables here:
      # - '--set-env-vars=CORS_ORIGINS=https://your-frontend.com'
      # - '--set-env-vars=postgres_user=your-user'
    id: 'deploy'
    waitFor: ['push-sha', 'push-latest']

images:
  - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/tareas-back:latest'

# Build configuration
timeout: '1800s'  # 30 minutes

options:
  machineType: 'E2_HIGHCPU_8'  # Use more powerful machine for faster builds
  logging: CLOUD_LOGGING_ONLY
