steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tareas-back:latest'
      - '.'
    id: 'build'
    
  # Push image with commit SHA
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
    id: 'push-sha'
    waitFor: ['build']
  
  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/tareas-back:latest'
    id: 'push-latest'
    waitFor: ['build']
  
  # Deploy to Cloud Run - Initial deploy without DB vars
  # Database and auth vars should be configured separately for security
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tareas-back'
      - '--image=gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--port=5000'
      - '--cpu=${_CPU}'
      - '--memory=${_MEMORY}'
      - '--timeout=${_TIMEOUT}'
      - '--min-instances=${_MIN_INSTANCES}'
      - '--max-instances=${_MAX_INSTANCES}'
      - '--allow-unauthenticated'
      - '--set-env-vars=CORS_ORIGINS=${_CORS_ORIGINS},CORS_ALLOW_CREDENTIALS=true,LOG_LEVEL=${_LOG_LEVEL},RUN_DB_SETUP=0,RUN_DB_CREATION=0'
    id: 'deploy'
    waitFor: ['push-sha', 'push-latest']

images:
  - 'gcr.io/$PROJECT_ID/tareas-back:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/tareas-back:latest'

# Substitution variables with defaults
substitutions:
  _REGION: 'us-west1'
  _CPU: '1'
  _MEMORY: '512Mi'
  _TIMEOUT: '300'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _CORS_ORIGINS: 'http://localhost:5173'
  _LOG_LEVEL: 'INFO'

# Build configuration
timeout: '1800s'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
